export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';
export const GET_PROFILE_DONE = 'GET_PROFILE_DONE';
export const GET_PROFILE_CLEAR = 'GET_PROFILE_CLEAR';
