export const SET_LOGIN = 'SET_LOGIN';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_FAILED = 'SET_LOGIN_FAILED';
export const SET_LOGIN_CLEAR = 'SET_LOGIN_CLEAR';
export const SET_LOGIN_DONE = 'SET_LOGIN_DONE';

export const SET_REGISTER = 'SET_REGISTER';
export const SET_REGISTER_SUCCESS = 'SET_REGISTER_SUCCESS';
export const SET_REGISTER_FAILED = 'SET_REGISTER_FAILED';
export const SET_REGISTER_CLEAR = 'SET_REGISTER_CLEAR';
export const SET_REGISTER_DONE = 'SET_REGISTER_DONE';

export const SET_AUTH = 'SET_AUTH';
export const SET_CLEAR_AUTH = 'SET_CLEAR_AUTH';
