export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILED = 'GET_POST_FAILED';
export const GET_POST_CLEAR = 'GET_POST_CLEAR';
export const GET_POST_DONE = 'GET_POST_DONE';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';
export const CREATE_POST_CLEAR = 'CREATE_POST_CLEAR';
export const CREATE_POST_DONE = 'CREATE_POST_DONE';

export const SET_POST_PROGRESS = 'SET_POST_PROGRESS';
